// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hkdsiivrjquuiekygfcu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhrZHNpaXZyanF1dWlla3lnZmN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2NTQ1MTQsImV4cCI6MjA2OTIzMDUxNH0.X2g5ESK9TuJva19Z-8QufbTA0StxucG6rV_XOS4EDu0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});